apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap-cluster
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: cluster-bootstrap
    repoURL: https://github.com/arunlalp/argocd-app-of-apps-cluster-bootstrap.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}